### ISSUE TITLE
Hope to support Large Biomes

### ISSUE THREAD

**Issue by Muggleee** [hube12/WitchHutFinder#1]
This is a very good program，and Hope to support Large Biomes，thank you

**Comment by hube12** [comment]
Ofc i can add that support, i am so sorry to never have seen any of the issues here

**Comment by hube12** [comment]
Done

**Comment by Muggleee** [comment]
Wow. Thank you

**Comment by Muggleee** [comment]
Thank you, but how to search in large biomes now, didn't see any instructions

**Comment by hube12** [comment]
In the latest release there is a zip called large biomes

**Comment by hube12** [comment]
its exactly the same as the old one except it has large biomes
